name: Android CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    name: Building app
    runs-on: ubuntu-latest
    steps:
      # Specify branch to checkout
      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          ref: 'master'

      # Setup JDK
      - name: 1. Settting up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Run your own gradle command to generate build.
      - name: 2. Runing build command
        run: ./gradlew bundleRelease

      # Check the code with ktlint
      - name: 3. Check the code with ktlint
        run: ./gradlew ktlintDebugCheck

      # Run Unit Tests
      - name: 4. Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # 4. Uplading build
      - name: 5. Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: app/build/outputs/bundle/release/app-release.aab

      # Send Slcak Notify Message
      - name: 6. Send Slcak Notify Message
        # 실패할때만 호출
        # if: failure()
        uses: 8398a7/action-slack@v2.6.0
        with:
          status: ${{job.status}}
          author_name: <github-action>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          # https://hooks:slack:com/services/T01S79TDE9E/B01RANBUJ0N/OhfdJ31KTYQ5ooWHWAxfwJeW:

  upload_to_internal_app_sharing:
    name: Uploading build to IAS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading build
        uses: actions/download-artifact@v2
        with:
          name: bundle
      - name: Uplaoding to IAS
        id: ias
        uses: sagar-viradiya/internal-app-sharing-action@v1.1.0
        with:
          # Your service account JSON GitHub secret
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          # Your package name
          packageName: 'beeasy.a90ms.actionsample'
          apkFilePath: 'app/build/outputs/bundle/release/app-release.aab'
      - name: Sharing on slack
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          # Your slack webhook GitHub secret
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          # Slack channel where you want to notify
          SLACK_CHANNEL: github-action
          SLACK_USERNAME: "90MS"
          SLACK_TITLE: "file download"
          SLACK_MESSAGE: ${{ steps.ias.outputs.downloadUrl }}
