name: Android CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Setup JDK
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Check the code with ktlint, you can remove this job if you don't use ktlint
      - name: Run Kotlin Linter
        run: ./gradlew ktlintStagingDebugCheck

      # Check the code with Android linter
       - name: Run Android Linter
        run: ./gradlew lintStagingDebug

       # Yun your unit tests
      - name: Run Unit Tests
        run: ./gradlew testStagingDebugUnitTest

      # Build apk
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      # Upload apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug
