name: Android CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  apk:
    name: actionSample CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Setup JDK
      - name: 1. set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Check the code with ktlint
      - name: 2. Check the code with ktlint
        run: ./gradlew ktlintDebugCheck

       # Run Unit Tests
      - name: 3. Run Unit Tests
        run: ./gradlew testDebugUnitTest

        # Build debug APK
      - name: 4. Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace


      # Send Slack Notify Message1
      - name: 5. Slack Notify Message
#        if: failure()
        uses: 8398a7/action-slack@v2.6.0
        with:
          status: ${{job.status}}
          author_name: <github-action>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_CHANNEL: github-action
          SLACK_COLOR: '#FF2D00'
          SLACK_USERNAME: 'Github Action'
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: Build Failure - ${{ github.event.pull_request.title }}
          SLACK_MESSAGE: PR Url - ${{ github.event.pull_request.url }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@master
#        env:
#          SLACK_CHANNEL: android-build
#          SLACK_COLOR: '#DD0000'
#          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
#          SLACK_MESSAGE: '${{ env.DEVELOP_VERSION }} 개발 빌드가 완료되었습니다'
#          SLACK_TITLE: '${{ env.DEVELOP_VERSION }}  개발버전 입니다.'
#          SLACK_USERNAME: 개발 개발
#          SLACK_WEBHOOK_URL: ${{ secrets.ANDROID_BUILD }}
#          SLACK_FOOTER: 개발버전 입니다.


      #https://hooks:
      #  slack:
      #   com/services/T01S79TDE9E/B01RANBUJ0N/OhfdJ31KTYQ5ooWHWAxfwJeW:

#      # Send Slcak Notify Message2
#      - name: action-slack
#        uses: 8398a7/action-slack@v2.6.0
#        with:
#          status: ${{job.status}}
#          author_name: <github-action>
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

      # Upload Debug APK
      - name: 6. Upload Debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug

#      # Send Slack File Upload
#      slack_upload_job:
#        runs-on: ubuntu-latest
#        name: 7. Send Slack File Upload
#        steps:
#          - name: Checkout
#            uses: actions/checkout@v1
#
#          - name: Upload to slack step
#            uses: adrey/slack-file-upload-action@master
#            with:
#              token: ${{ secrets.SLACK_TOKEN }}
#              path: app/build/outputs/apk/debug
#              channel: github-action
