name: Android CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  apk:
    name: actionSample CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Setup JDK
      - name: 1. set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Check the code with ktlint
      - name: 2. Check the code with ktlint
        run: ./gradlew ktlintDebugCheck

       # Run Unit Tests
      - name: 3. Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Build debug APK
      - name: 4. Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

#      # Send Slack Notify Message
#      - name: Slack Notify Message
#        if: failure()
#        uses: rtCamp/action-slack-notify@v2.1.0
#        env:
#          SLACK_CHANNEL: group-dev
#          SLACK_COLOR: '#FF2D00'
#          SLACK_USERNAME: 'Github Action'
#          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
#          SLACK_TITLE: Build Failure - ${{ github.event.pull_request.title }}
#          SLACK_MESSAGE: PR Url - ${{ github.event.pull_request.url }}
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      # Upload APK
      - name: 5. Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug
