name: Android CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  apk:
    name: actionSample CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Setup JDK
      - name: 1. set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Check the code with ktlint
      - name: 2. Check the code with ktlint
        run: ./gradlew ktlintDebugCheck

       # Run Unit Tests
      - name: 3. Run Unit Tests
        run: ./gradlew testDebugUnitTest

        # Build debug APK
      - name: 4. Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

        # Send Slcak Notify Message
      - name: 5. Send Slcak Notify Message
        # if: failure()
        uses: 8398a7/action-slack@v2.6.0
        with:
          status: ${{job.status}}
          author_name: <github-action>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      # https://hooks:slack:com/services/T01S79TDE9E/B01RANBUJ0N/OhfdJ31KTYQ5ooWHWAxfwJeW:

      # Upload Debug APK
      - name: 6. Upload Debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

  build:
    name: Building app
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          # Specify branch to checkout
          ref: '[branch_name]'
      - name: Settting up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Runing build command
        # Run your own gradle command to generate build.
        run: ./gradlew assembleDebug
      - name: Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk


  upload_to_internal_app_sharing:
    name: Uploading build to IAS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading build
        uses: actions/download-artifact@v2
        with:
          name: apk
      - name: Uplaoding to IAS
        id: ias
        uses: sagar-viradiya/internal-app-sharing-action@v1.1.0
        with:
          # Your service account JSON GitHub secret
          serviceAccountJsonPlainText: ${{ secrets.GITHUB_TOKEN }}
          # Your package name
          packageName: '[beeasy.a90ms.actionsample]'
          aabFilePath: app/build/outputs/apk/debug
      - name: Sharing on slack
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          # Your slack webhook GitHub secret
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          # Slack channel where you want to notify
          SLACK_CHANNEL: [your-channel]
          SLACK_USERNAME: "JARVIS"
          SLACK_TITLE: "Internal testing build"
          SLACK_MESSAGE: ${{ steps.ias.outputs.downloadUrl }}

#      # Send Slack File Upload
#      slack_upload_job:
#        runs-on: ubuntu-latest
#        name: 7. Send Slack File Upload
#        steps:
#          - name: Checkout
#            uses: actions/checkout@v1
#
#          - name: Upload to slack step
#            uses: adrey/slack-file-upload-action@master
#            with:
#              token: ${{ secrets.SLACK_TOKEN }}
#              path: app/build/outputs/apk/debug
#              channel: github-action
