name: Android CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  apk:
    name: actionSample CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Setup JDK
      - name: 1. set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Check the code with ktlint
      - name: 2. Check the code with ktlint
        run: ./gradlew ktlintDebugCheck

       # Run Unit Tests
      - name: 3. Run Unit Tests
        run: ./gradlew testDebugUnitTest

        # Build debug APK
      - name: 4. Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      # Upload Debug APK
      - name: 5. Upload Debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

        # Send Slcak Notify Message
      - name: 6. Send Slcak Notify Message
        # 실패할때만 호출
        # if: failure()
        uses: 8398a7/action-slack@v2.6.0
        with:
          status: ${{job.status}}
          author_name: <github-action>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      # https://hooks:slack:com/services/T01S79TDE9E/B01RANBUJ0N/OhfdJ31KTYQ5ooWHWAxfwJeW:

  upload_to_internal_app_sharing:
    name: Uploading build to IAS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading build
        uses: actions/download-artifact@v2
        with:
          name: app
      - name: Uplaoding to IAS
        id: ias
      uses: sagar-viradiya/internal-app-sharing-action@v1.1.0
      with:
        # Your service account JSON GitHub secret
        # serviceAccountJsonPlainText: ${{ secrets.[your-github-service-acc-json-secret] }}
          # Your package name
          packageName: 'beeasy.a90ms.actionsample'
          apkFilePath: 'app/build/outputs/apk/debug/app-debug.apk'
        - name: Sharing on slack
          uses: rtCamp/action-slack-notify@v2.1.0
          env:
            # Your slack webhook GitHub secret
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
            # Slack channel where you want to notify
            SLACK_CHANNEL: [your-channel]
            SLACK_USERNAME: "90MS"
            SLACK_TITLE: "file download"
            SLACK_MESSAGE: ${{ steps.ias.outputs.downloadUrl }}

      - name: END
