name: Build, Upload to IAS and share on slack.
on:
  push:
    branches:
      # Specify branch from where you are sharing build
      - master
jobs:
  build:
    name: Building app
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          # Specify branch to checkout          
          ref: 'master'
      - name: Settting up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Runing build command
        # Run your own gradle command to generate build.
        run: ./gradlew assembleDebug
      - name: Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk


  upload_to_internal_app_sharing:
    name: Uploading build to IAS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading build
        uses: actions/download-artifact@v2
        with:
          name: app
      - name: Uplaoding to IAS
        id: ias
      	uses: sagar-viradiya/internal-app-sharing-action@v1.1.0
      	with:
          # Your service account JSON GitHub secret
      	  # serviceAccountJsonPlainText: ${{ secrets.[your-github-service-acc-json-secret] }}
          # Your package name
          packageName: 'beeasy.a90ms.actionsample'
          apkFilePath: 'app-debug.apk'
      - name: Sharing on slack
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          # Your slack webhook GitHub secret
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          # Slack channel where you want to notify
          SLACK_CHANNEL: github-action
          SLACK_USERNAME: "90MS"
          SLACK_TITLE: "apk file upload"
          SLACK_MESSAGE: ${{ steps.ias.outputs.downloadUrl }}
